version: '3'
services:

  postgres:
      image: postgres:15.7
      restart: always
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        PGDATA: /var/lib/postgresql/data
      volumes:
        - ./data:/var/lib/postgresql/data
      ports:
        - 5432:5432

  pgadmin4:
      image: elestio/pgadmin:latest
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: d.badyanov@outlook.com
        PGADMIN_DEFAULT_PASSWORD: postgres
        PGADMIN_LISTEN_PORT: 8080
      ports:
        - 8080:8080
      volumes:
        - ./servers.json:/pgadmin4/servers.json